# Generated by Django 4.1.4 on 2022-12-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='Адрес',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='Город',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='Имя',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='Индекс',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='Фамилия',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='Эл_почта',
        ),
    ]
